name: push-and-upload

on:
  push:
    branches: [ master ]


jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Jar
        run: mvn clean install

      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context:
          push: true
          tags: peteralmgren/peter-image:${{ github.run_number }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: target/*.jar