name: Greeter

on:
  workflow_dispatch:
    push:
      branches:
        -master
      pull_request:

jobs:
  greet:
    runs-on: ubuntu-latest



    steps:
      - name: step 1, Greet
        run: echo Hello ${{ secrets.DOCKER_KEY }}

      - name: Step 2
        run: echo Hej då
